### ISSUE TITLE
already initialized constant Usps::Base::SERVICE_CODE_PREFIX

### ISSUE THREAD

**Issue by MisinformedDNA** [spree-contrib/spree_active_shipping#200] opened 2015-01-08 19:47 UTC
After adding `spree_active_shipping`, I got the following warnings when I start up the server (it still loads)

```
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_active_shipping-e8bd3aa120ba/app/models/spree/calculator/shipping/usps/base.rb:6: warning: already initialized constant Spree::Calculator::Shipping::Usps::Base::SERVICE_CODE_PREFIX
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_active_shipping-e8bd3aa120ba/app/models/spree/calculator/shipping/usps/base.rb:6: warning: previous definition of SERVICE_CODE_PREFIX was here
```

Any ideas what is causing this? 

Full server log:
```
vagrant@vagrant:/vagrant/dragondoor$ rails s
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/app_rails_loader.rb:37: warning: Insecure world writable dir /vagrant/dragondoor in PATH, mode 040777
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:302: warning: Insecure world writable dir /vagrant/dragondoor in PATH, mode 040777
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:302: warning: Insecure world writable dir /vagrant/dragondoor in PATH, mode 040777
=> Booting WEBrick
=> Rails 4.1.8 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_active_shipping-e8bd3aa120ba/app/models/spree/calculator/shipping/usps/base.rb:6: warning: already initialized constant Spree::Calculator::Shipping::Usps::Base::SERVICE_CODE_PREFIX
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_active_shipping-e8bd3aa120ba/app/models/spree/calculator/shipping/usps/base.rb:6: warning: previous definition of SERVICE_CODE_PREFIX was here
[2015-01-08 19:38:55] INFO  WEBrick 1.3.1
[2015-01-08 19:38:55] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux]
[2015-01-08 19:38:55] INFO  WEBrick::HTTPServer#start: pid=23982 port=3000
```

**Comment by pelargir** [comment] 2015-01-20 15:56
I'm seeing these warnings to, after upgrading to the 2-3-stable branch.

**Comment by pelargir** [comment] 2015-01-20 19:20
Seems to be caused by engine.rb which #constantizes the calculator classes on line 34. This must auto-load the Spree::Calculator::Shipping::Usps::Base class since express_mail.rb subclasses it. But then on line 12 of engine.rb the Usps::Base class gets loaded a second time.

**Comment by aravindratna93** [comment] 2015-05-05 08:53
Having the Same Problem with me Guys, 
Please Help Me Out!!!

![capture](https://cloud.githubusercontent.com/assets/8010770/7469521/47931e28-f332-11e4-9843-c780ccd2e5df.PNG)

**Comment by philbattos** [comment] 2015-05-18 00:47
Since upgrading Spree from 2.2 to 3.0, I am seeing these warnings too. The fix does not seem to change anything.

**Comment by mleglise** [comment] 2015-06-16 00:34
The fix for this bug is now available in all of the maintained branches: master, 3-0-stable, 2-4-stable, 2-3-stable. Thanks to @BenMorganIO for solving it.

If anyone runs into this bug using the updated code, please post here.

**Closed by mleglise** 2015-06-16 00:34 UTC
Labels: bug
